### ISSUE TITLE
pb-for-desktop doesn't show up

### ISSUE THREAD

**Issue by davisnando** [sidneys/pb-for-desktop#72] opened 2017-11-24 09:55 UTC
## 🤷🏽‍♂️ Current Behaviour

When I start pb-for-desktop it shows the window that says connecting after that screen the window disapeared. There is nothing in icon tray. When I kill pb-for-desktop and then try again it does the same thing and when I start it in the terminal it doesn't log anything

## 🎯 Expected Behaviour

Program should show up

## 👟 Steps to Reproduce (S2R)

1. Start pb-for-desktop
2. setup so that the program works
3. close program
4. start program again

## 🏡 Environmental Context

**App Version**
latest
**Installation Type** 
 Installation via package manager (Linux)
**Operating System**
Linux 17.04

**Comment by davisnando** [comment] 2017-11-24 10:15
It is fixed when you change your desktop environment start the program there and switch back to your desktop environment. I think it won't show up in my icon tray. I am using budgie as my environment

**Comment by sidneys** [comment] 2018-03-19 21:29
This is a duplicate of #79, the discussion will be continued over there.

Cheers,
S

**Closed as completed by sidneys** 2018-03-19 21:29 UTC
Labels: bug report, duplicate, Linux
