### ISSUE TITLE
Error  with 'Show PB for Desktop' menu, MacOS Catalina  10.15.2 

### ISSUE THREAD

**Issue by xraynaud** [sidneys/pb-for-desktop#117] opened 2020-01-23 13:40 UTC
As stated in the title, when I click on 'Show PB for Desktop' menu (top bar), i get the following error message: 

A Javascript error occured in the main process
Uncaught exception: 
TypeError: getMaineWindow.show is not  a function 
  at click (/Application/PB for Desktop.app/Contents/Resources/app.asar/app/scripts/main-process/menus/tray-menu.js:109:31) 
  at MenuItem.click (electron/js2C/browser_init.js:1516:9) 
  at Function.executeCommand (electron/js2C/browser_init.js:1777:13)

## 🎯 Expected Behaviour
I'm not sure. Show the same window as when clicking on the dock icon ? 

## 👟 Steps to Reproduce (S2R)
1. Launch MacOS Catalina
2. Launch PB for Desktop
3. Click on the top bar PB for Desktop and select 'Show PB for Desktop'

## 🏡 Environmental Context
**App Version**
v10.5.0 but also occured in previous version
**Installation Type** 
Setup
MacOS 10.15.2 Catalina

**Comment by MockingMagician** [comment] 2020-01-27 12:52
I have same issue on ubuntu 18.10

![Capture d’écran de 2020-01-27 13-51-12](https://user-images.githubusercontent.com/33423809/73176225-343c4700-410c-11ea-9ecf-0b2d7128ebb1.png)

:/

**Comment by MockingMagician** [comment] 2020-01-29 12:45
Can be fixed with this PR https://github.com/sidneys/pb-for-desktop/pull/118

**Comment by xraynaud** [comment] 2020-02-07 21:24
@MockingMagician this works. Thanks.

**Comment by joeherold** [comment] 2020-04-29 07:42
same here on 10.15.4

**Comment by mutachre** [comment] 2020-06-05 20:50
Same here (MacOS Catilina 10.15.5).

<img width="460" alt="2020-06-05_22-46-09 603" src="https://user-images.githubusercontent.com/62408551/83921499-c4eff700-a77e-11ea-9a88-50473846bae5.png">

**Comment by joeherold** [comment] 2020-06-06 05:56
You can fix it for yourself as a workaround.
Unpack app.asar and do the PR #118.
Then pack it back to app.asar

npx asar extract app.asar app

npx asar pack app app.asar

**Comment by ZeekWorld** [comment] 2020-07-15 04:17
Can someone explain a little better how to do the fix above with the npx command? I am also getting the error message on Mac OS Catalina.
Perhaps a step by step on how to apply this fix would help users like me.
Thanks in advance.

**Comment by omaishar** [comment] 2020-07-29 09:30
Same here (Catalina 10.15.6)
![image](https://user-images.githubusercontent.com/14070203/88783289-410f2580-d197-11ea-9139-796fefca9f88.png)

**Comment by sidneys** [comment] 2020-08-20 15:36
@xraynaud @MockingMagician @joeherold @Mutachre 

Thank you for the report, your work and the related pull request.

This issue should be resolved as per the [new release](https://github.com/sidneys/pb-for-desktop/releases), which was just published, and seems to be a duplicate of identical to https://github.com/sidneys/pb-for-desktop/issues/116.

Please review the changes and file a new issue accordingly if the problem should reoccur.

Kind regards,
S

**Closed as completed by sidneys** 2020-08-20 15:36 UTC
Labels: bug report, macOS
