### ISSUE TITLE
High Energy/CPU usage after reconnecting on macOS

### ISSUE THREAD

**Issue by electronic-dk** [sidneys/pb-for-desktop#31] opened 2017-03-23 09:19 UTC
## 🤷🏽‍♂️ Current Behaviour
Similar to https://github.com/sidneys/pb-for-desktop/issues/25
The energy consumption is low after start.
After I select "Reconnect..." tray menu item or if the app reconnects automatically, one of the helper processes starts to use a lot of CPU/Energy (pretty much as in https://github.com/sidneys/pb-for-desktop/issues/25).
Logging out and then back in helps to resolve it until a next reconnection

## 🎯 Expected Behaviour
CPU/Energy consumption after a reconnection remains as low as it was before the reconnection.

## 👟 Steps to Reproduce (S2R)
 1. Launch the app and log in
 2. Select "Reconnect..." form the tray menu

## 🏡 Environmental Context
**App Version**
v4.3.0
**Installation Type** 
Disk image
**Operating System**
masOS Sierra 10.12.3

**Comment by sidneys** [comment] 2017-04-01 18:06
@electronic-dk 

Thanks for the report. Can you please test this again with the latest release? Some core components related to performance have been replaced. Thanks.
--> [Link](../releases)

**Comment by electronic-dk** [comment] 2017-04-03 07:06
@sidneys unfortunately, I'm still experiencing this issue. 
<img width="454" alt="screen shot 2017-04-03 at 10 06 14" src="https://cloud.githubusercontent.com/assets/2945527/24598648/2a6558f8-1855-11e7-86da-2fb81ba9dfaa.png">

I'll try to investigate more

**Comment by electronic-dk** [comment] 2017-04-04 15:36
@sidneys I'm not experiencing this issue in v5.0.0 anymore. Thanks so much for fixing it 👍 

(EDIT: Looks like I was too optimistic, the issue still persists)
<img width="430" alt="screen shot 2017-04-04 at 18 45 03" src="https://cloud.githubusercontent.com/assets/2945527/24665627/a2a7019c-1966-11e7-9d27-1d5fff8df4dc.png">

**Comment by sidneys** [comment] 2017-04-09 15:07
@electronic-dk Any updates on this? I couldn't reproduces this the releases after 5.3.0.

**Comment by sidneys** [comment] 2017-04-09 18:50
@electronic-dk 

This is not reproducible anymore - if it reoccurs, please comment or create a new issue. Closing.

**Closed as completed by sidneys** 2017-04-09 18:50 UTC
Labels: macOS, needs reply, performance
