### ISSUE TITLE
Advancing PB4D connectivity management

### ISSUE THREAD

**Issue by erezhdd** [sidneys/pb-for-desktop#26] opened 2017-03-21 09:46 UTC
**PB4D 4.1.0** / Ubuntu 16.04:
PB for desktop is quite mature and usable. An even further improvement would be to make the connection status **more tangible for the user**, Skype-style. 
IMHO, this implies adding a set of icons/icon decorations to represent the connectivity status of PB4D client at the tray icon. For example, when the client is disconnected, we can add a small "x" at the icon corner. When attempting reconnection (either manually or automatically), we can add a small "play" triangle at the corner. When connection is established, the tray icon should have no decorations at all. Alternatively, we can play with the colors: green background for operational, gray background for disconnected, yellow background for attempting reconnection . The icon changes can be accompanied by a mouse hover message.

**Comment by sidneys** [comment] 2017-04-04 04:24
The new offline icon is in v5.0.0. [Please test.](../releases)

**Comment by erezhdd** [comment] 2017-04-04 07:44
Installed. Basic regression tests - startup, connection - PASS.
However, I pressed on "disconnect", clicked "Yes" and the icon remained the same (green).
Either disconnect is not working or the offline icon is not properly configured.
Thank you for your the effort!

**Comment by erezhdd** [comment] 2017-04-04 07:48
It turns out that after disconnect, reconnect requires full login - username + password. Would it be possible to save those credentials, so that reconnecting is the same as a fresh start of the app?

**Comment by erezhdd** [comment] 2017-04-04 07:50
Forgot the important stuff, per my previous comment - disconnect is WORKING. So it's a matter of improperly configured status icon, that needs to show "offline".

**Comment by sidneys** [comment] 2017-04-06 07:22
@erezhdd 
Cannot reproduce the **reconnect requires full login** issue. `Reconnect` merely restarts the application, leaving everything untouched. `Log out`resets configuration and cache and therefore requires a new login.

**Comment by sidneys** [comment] 2017-04-09 18:46
@erezhdd 

Does this issue still occur in [v5.4.4](../releases)?
Will close otherwise.

**Comment by erezhdd** [comment] 2017-04-09 20:39
Will verify tomorrow

**Comment by sidneys** [comment] 2017-04-18 16:12
@erezhdd Closing this until further input.

**Closed as completed by sidneys** 2017-04-18 16:12 UTC
Labels: feature request, Linux, needs reply
