### ISSUE TITLE
Not receiving notifications on macOS

### ISSUE THREAD

**Issue by charles-001** [sidneys/pb-for-desktop#109] opened 2019-08-09 23:31 UTC
## 🤷🏽‍♂️ Current Behaviour

I'm not receiving notifications on my desktop.

I see the "PB for Desktop" device, but everything that is sent from the desktop or sent to that device from my phone gets stucks in "Sending" status.

## 🎯 Expected Behaviour

Receive a desktop notification whenever my phone does

## 🏡 Environmental Context

**App Version**
9.5.0
**Installation Type** 
Setup
**Operating System**
macOS Mojave 10.14.6

**Comment by GodLesZ** [comment] 2019-09-02 04:55
Duplicate of #100

**Comment by sidneys** [comment] 2019-11-14 13:54
Duplicate of #100, indeed. Thanks, @GodLesZ. Closing.

**Closed as completed by sidneys** 2019-11-14 13:54 UTC
