### ISSUE TITLE
A queue of missed but still valid events

### ISSUE THREAD

**Issue by erezhdd** [sidneys/pb-for-desktop#53] opened 2017-06-05 18:09 UTC
Ubuntu 16.04, PB4D 5.9.4
Once the app reconnects, how can I view events that are still shown on the phone but were missed by me, e.g., when the laptop was suspended? Does the PB service provide support for that?

**Comment by pongraczi** [comment] 2017-09-19 08:40
Hmmm, is it the same as I reported some minutes ago?  
#66

**Comment by erezhdd** [comment] 2017-09-19 09:33
Yes, sort of.. your item is more detailed and discusses the general case of missing out messages, so I think I would close this one as a duplicate of #66. Up to Sidney's decision.

**Comment by sidneys** [comment] 2017-10-31 20:38
@erezhdd @pongraczi 

This indeed is a duplicate of #66, closing.

**Closed as completed by sidneys** 2017-10-31 20:38 UTC
Labels: question, Linux
