### ISSUE TITLE
Green window

### ISSUE THREAD

**Issue by rcastbergw** [sidneys/pb-for-desktop#8] opened 2016-09-26 11:20 UTC
After installing i tried logging in, and was presented with the google/facebook choice, choosing google and after entering my username the window goes green.

Using the mouse i can drag parts of the window and can see that it is requesting my password which i am able to add, though i can't get any further as i was unable to read the next google authenticator screen.

**Comment by sidneys** [comment] 2016-10-08 10:52
Hi @rcastbergw, thanks for your report. Can you provide these details:
- app version
- operating system & version

kind regards, S

**Comment by rcastbergw** [comment] 2016-10-10 08:20
Package.json says :   "version": "2.3.0",
I am running kubuntu, lsb_release says  "Description:    Ubuntu 16.04.1 LTS"

My home machine running Kubuntu 15.10, runs fine.

Regards, Rene Castberg

**Comment by sidneys** [comment] 2016-10-10 18:06
@rcastbergw Thanks for the details! Can you try if the recent release fixed the issue:

https://github.com/sidneys/pb-for-desktop/releases/tag/v2.5.1

cheers

**Comment by rcastbergw** [comment] 2016-10-13 14:57
Just tried the latest release, and all i get is a spinning pushbullet logo and no login

**Comment by sidneys** [comment] 2016-10-16 02:20
@rcastbergw Did you re-test with 2.5.1 or a more current release? We know the issue, but cannot reproduce the issue with the current 2.8.0 release.

**Comment by rcastbergw** [comment] 2016-10-17 07:25
Just tried the 2.8 release, spinning logo is gone, but i still get a green window. I am able to see that the google login window is below the green if i select something, then i am able to view it in my clipboard viewer. (it is prompting me if i want an org or invidual account, and  authenticator (where i get stuck))

**Comment by sidneys** [comment] 2016-11-28 13:41
@rcastbergw  fixed in 2.9.2

**Closed as completed by sidneys** 2016-11-28 13:41 UTC
Labels: bug report, help wanted, question, Linux
