### ISSUE TITLE
Implement the Reply-feature

### ISSUE THREAD

**Issue by capstan1** [sidneys/pb-for-desktop#62] opened 2017-07-22 13:13 UTC
## 🤷🏽‍♂️ Current Behaviour

Notifications are mirrored to the PC's notification-system. On Click on the notification nothing happens/it just closes.

## 🎯 Expected Behaviour

When clicking on the notification the "Respond"-Window of Pushbullet should open giving me the possibility of responding the message (e.g. whatsapp). (If I use the Chrome-Extension together with the new native-notifications exactly that happens)

**Comment by sidneys** [comment] 2017-09-02 05:13
This issue is a duplicate of #51

**Closed as completed** 2017-09-02 05:13 UTC
Labels: duplicate

**Comment by capstan1** [comment] 2017-09-02 05:46
Not exactly an duplicate imho, as notifications in Linux don't allow inline reply or buttons as in #51.

**Comment by Iiari** [comment] 2020-05-04 21:23
Any way to revisit this?  Linux definitely allows inline reply and other buttons now.  This photo shows the PB Desktop vs Chrome-to-native (KDE Plasma) handling of the same PB notification:  https://i.imgur.com/bQC45y8.png

It would make for an epic improvement.
