### ISSUE TITLE
Android SMS not showing on MacOS 

### ISSUE THREAD

**Issue by drew5494** [sidneys/pb-for-desktop#78] opened 2018-02-28 19:22 UTC
## 🤷🏽‍♂️ Current Behaviour
When running version 6.8.1 on MacOS 10.13.3, all other notifications are visible except for SMS.  
I still see the icon count correctly and when opening the app they are visible.  
Rolling back to 6.5.1 works again.
## 🎯 Expected Behaviour
All notifications are visible including SMS.

## 👟 Steps to Reproduce (S2R)
1.  Install version 6.8.1 on MacOS 10.13.3
2. Receive SMS

**App Version**
v6.8.1
**Installation Type** 
Setup
**Operating System**
MacOS 10.13.3

**Comment by sidneys** [comment] 2018-03-19 22:24
@drew5494 

Thanks for your feedback. However, i could not reproduce this issue using the current prerelease version (6.9.0), receiving SMS and replying via notification actions is working on High Sierra as designed. It seems this could be related to an upstream issue regarding the notification subsystem, thus you should re-test this with this upcoming release at the latest. 

Could you add additional details regarding your Android environment?
I tested with Android 7.1.1 (Google Android Studio Emulator, Play Store Image) with the latest Pushbullet for Android app.

Cheers,
S

**Comment by sidneys** [comment] 2018-03-22 00:53
@drew5494 

This issue was addressed in [v6.9.0](https://github.com/sidneys/pb-for-desktop/releases).

Cheers,
S

**Closed as completed by sidneys** 2018-03-22 00:53 UTC
Labels: bug report, macOS, needs reply

**Comment by drew5494** [comment] 2018-03-22 01:35
For some reason it doesn't work for me im using the latest version of PB for desktop and the latest version of MacOS .  I have a Note 8 running android 8.0.
